### ISSUE TITLE
Problem with serial

### ISSUE THREAD

**Issue by andeflyever** [bborncr/nextion#20]
Hi bborncr,
I update all the instructions (readme.md) but the compiler show: expected identifier before numeric constant. I use Nextion 4.3" with Arduino Mega 2560.
This is my code:

#include <Nextion.h>

#define nextion HardwareSerial

nextion myNextion(nextion, 9600); // error compiler

boolean button1State;
boolean button2State;

// sensor "progress" bar
int x = 56;
int y = 321;
int width = 195;
int height = 8;

int old_sensor_value = 0;

void setup() {
//  Serial.begin(9600);
  myNextion.init();
}

void loop() {

  String message = myNextion.listen();

  if (message == "65 0 2 0 ffff ffff ffff") {
    myNextion.buttonToggle(button1State, "b0", 0, 2);
  }
  if (message == "65 0 3 0 ffff ffff ffff") {
    myNextion.buttonToggle(button2State, "b1", 0, 2);
  }

  int sensor = 0;

  for (int i = 0; i < 10 ; i ++) { // get average
    sensor += analogRead(A0);
  }
  sensor = sensor / 10;

  if (abs(sensor - old_sensor_value) > 20) {
    old_sensor_value = sensor;

    int scaled_value = map(sensor, 0, 1023, 0, 100); // always map value from 0 to 100

    myNextion.updateProgressBar(x, y, width, height, scaled_value, 0, 2); // update the progress bar
    myNextion.setComponentText("t0", String(sensor));  // update text using original sensor value

  }
}

**Comment by bborncr** [comment]
There are various syntax errors in the pasted code. The library isn't included.
